const GET_DATA = 'GET_DATA'
const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
const GET_DATA_FAILURE = 'GET_DATA_FAILURE'
const SET_FAVOURITE = 'SET_FAVOURITE'

export {GET_DATA, GET_DATA_SUCCESS, GET_DATA_FAILURE, SET_FAVOURITE}